Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [58]:
import numpy as np

def build_ATVandermonde_Matrix(input_vector, n, increasing=False):
    
    if not increasing: #to print the output vector in an decreasing order
        ouput_matrix = np.array([x**(n-i-1) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    elif increasing: #to print the output vector in an increasing order
        ouput_matrix = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    
    return ouput_matrix


# We will iterate over each number in the given input array which is in_vector and the the iteration count is n times 
# where in 'n' is the number of columns in the o/p matrix and output is an intermediate vector. 

in_vector = np.array([1,2,3,4,5])
no_of_columns = 3
op_matrix_in_decreasing_order = build_ATVandermonde_Matrix(in_vector,no_of_columns,False)
op_matrix_in_increasing_order = build_ATVandermonde_Matrix(in_vector,no_of_columns,True)

print("The input array is:",in_vector,"\n")
print("Number of columns in output matrix are:",no_of_columns,"\n")
print("ATVandermonde matrix of the input array in decreasing order of powers is:-\n",op_matrix_in_decreasing_order,"\n")
print("ATVandermonde matrix of the input array in increasing order of powers is:-\n",op_matrix_in_increasing_order,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix are: 3 

ATVandermonde matrix of the input array in decreasing order of powers is:-
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

ATVandermonde matrix of the input array in increasing order of powers is:-
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [60]:
def mov_avg (i_list, k):
    tot_sum, moving_aves = [0], []
    for i, x in enumerate(i_list, 1):
        
        tot_sum.append(tot_sum[i-1] + x) # summing up all the values one by one and appending it back to the list
        
        if i>=k:
            temp_moving_ave = round(((tot_sum[i] - tot_sum[i-k])/k),2) #computing the moving avg
            moving_aves.append(temp_moving_ave) # listing the moving average as an single array
    
    print("Moving average values list is:- ", str(moving_aves))
    print("Length of the input list is (n-k+1):- ", len(moving_aves))
    
input_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3

mov_avg(input_list,k)

Moving average values list is:-  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the input list is (n-k+1):-  11
